### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by samburgers** [fabrica-wp/fabrica-dev-kit#1]
Hi, this looks really awesome. 

Which folder should we run something like `yarn add vue` from? If we want to add the library to `package.json` dependencies?

**Comment by tiojoca** [comment]
Hi, thanks @samburgers !

Client-side dependencies like Vue.js should be added on the `dev/src/` folder. If you need any extra tools in the build process they should be added to the `package.json` in `dev/`.

We'll be sure to make that clearer in the documentation.

**Comment by samburgers** [comment]
Excellent.... and woops, on initial look I had thought `dev-starter/` was the place to build to start building a theme due to the `dev/` folder being ignored. It's very clear now. Thanks for the reply!
