### ISSUE TITLE
Error while running wpconfig() task

### ISSUE THREAD

**Issue by maxperei** [fabrica-wp/fabrica-dev-kit#15]
hi there,
when i run `gulp` for the first time in `/dev` after a complete and successful `./setup.rb` i got this message
```
Error: Command failed: docker exec container_wp wp option get siteurl
```
and when i execute `docker exec container_wp wp option get siteurl` i should return something like `http://localhost:32769` but nothing happen...

i'm trying to share a theme i made with FDK, but i don't know how to deal with docker

**Comment by maxperei** [comment]
also when i go to the `http://localhost:327**` i got this : 
<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/7437661/27228588-80db2c3e-52a8-11e7-9415-22e329183662.png">

**Comment by fewerflatlands** [comment]
Hi @maxperei, could you paste the full output from `gulp` please?

**Comment by maxperei** [comment]
hi andrew 😌 
[output.txt](https://github.com/fabrica-wp/fabrica-dev-kit/files/1080914/output.txt)

**Comment by fewerflatlands** [comment]
Did you make any changes in the `src` folder (specifically, PHP) after setup?

**Comment by maxperei** [comment]
nothing at all

**Comment by fewerflatlands** [comment]
and this happens the same every time you run `gulp`?

**Comment by maxperei** [comment]
yes unfortunately, i did not experienced this error with the previous version of FDK

**Comment by fewerflatlands** [comment]
could you paste a screengrab of the contents of the `dev/build/` folder?

**Comment by maxperei** [comment]
here it is : 
<img width="237" alt="screenshot" src="https://user-images.githubusercontent.com/7437661/27231424-de4088f6-52b2-11e7-893a-aab83950418d.png">

**Comment by tiojoca** [comment]
Is there a `vendor/` in `dev/src/includes/`? Can you try and running `composer install` there?

**Comment by maxperei** [comment]
of course i should launch `composer install` from the very beginning, thank you

**Comment by fewerflatlands** [comment]
@maxperei `setup.rb` runs `composer install` automatically... did you get any error messages during the original install? Let us know what happens next time you set up a project? Thanks.
