### ISSUE TITLE
plugin development

### ISSUE THREAD

**Issue by karneaud** [fabrica-wp/fabrica-dev-kit#17]
I have a project in which I need both theme and plugin development. Can Fabrica handle this? Also can I use it without the template engines? Straight vanilla?

**Comment by tiojoca** [comment]
Hi @karneaud, this is something that we've added recently but is still undocumented. You can use the `imports.yml` file in the `dev/` folder to set the paths for the plugins that should be copied to the appropriate WordPress container folder, as well as some options like which files in these paths to watch for changes, and which to include and exclude when copying (as described in the file comments). This will only copy the plugins' files and won't process them in any way. As a newly-added feature we'd love to know what you think of it and how it works for you.

We don't have plans to make a vanilla version or option in Fabrica Dev Kit at the moment but you should be able to achieve this by simply editing `gulpfile.js`. We think of this file as project-specific to be adapted whenever necessary to fit each project needs.

**Comment by karneaud** [comment]
Awesome here man. Wish you had said this sooner. The "twig" template was a bit much for me hence my hesitation and adopting another starter kit. If there were a more modular way to integrate some of the blocks it would be more attractive. This kit could me more useful for single page apps though. Would look at it for future endeavours
