### ISSUE TITLE
[how-to] Mac OS and docker-machine

### ISSUE THREAD

**Issue by stefanorg** [fabrica-wp/fabrica-dev-kit#18]
Hi,
on osx, i use the docker-machine to start the docker deamon. 
The fabrica setup  use localhost by default, there's a way to change the string "localhost" to use the ip or the dns local name (/etc/hosts) of the dev machine for example "fabrica.dev.local" setting that local dns in /etc/hosts

thanks.

**Comment by tiojoca** [comment]
Hi @stefanorg, this is something we'd love to do but unfortunately macOS' version of Docker does not allow us to set custom IP addresses to containers. We would need this to attribute the custom hostname in `/etc/hosts`.
