### ISSUE TITLE
Missing .gitignore after a freshly initialized project

### ISSUE THREAD

**Issue by zomars** [fabrica-wp/fabrica-dev-kit#19]
Quoting the README: 

"To begin version control on your project run git init in the project folder. This will track not only your source code but also the corresponding build script and names of the modules needed to compile it into an active theme."

But as soon as I run `git init` I noticed that there is not a default `.gitignore` file as it was with the previous version.

**Comment by tiojoca** [comment]
Did you run `fdk init` and `fdk setup` to setup the project? `fdk setup` should copy a default `.gitignore` file to your project folder in the beginning of the process.

**Comment by zomars** [comment]
Yes, I've run both commands on two fresh projects and in both cases I've had to add the gitignore manually.

**Comment by dsuriano** [comment]
**+1** on missing `.gitignore` in a freshly initialized project after running `fdk init` then `fdk setup`.

**Comment by fewerflatlands** [comment]
Hi all, thanks for the feedback – this appears to be an NPM known issue, we're fixing it and will publish an update shortly.
