### ISSUE TITLE
Is there a preferred way to add a PHP extension to docker?

### ISSUE THREAD

**Issue by zomars** [fabrica-wp/fabrica-dev-kit#21]
I've tried modifying the Dockerfile but no apparent changes are showing up.

**Comment by zomars** [comment]
To be precise I'm trying to install the `intl` so I can use the `NumberFormatter`. Sorry If this is not the place to ask this, but I've already tried reading all docker docs, but the way FDK runs docker it's a little bit confusing for a newcomer like myself.

**Comment by tiojoca** [comment]
Have you tried running PECL on the container shell after the project has been set up?

**Comment by zomars** [comment]
@tiojoca care to give an example?

**Comment by tiojoca** [comment]
In general you can just start the shell with root user and run `pecl install` there:
```
docker-compose exec --user root wp /bin/bash
pecl install <package-name>
```

It seems for `intl` it is better to use `apt-get` instead:
```
docker-compose exec --user root wp /bin/bash
sudo apt-get update
sudo apt-get install php5-intl
```

You might have to restart the WP container afterwards for the changes to take effect.
