### ISSUE TITLE
postcssImport does not allow nesting

### ISSUE THREAD

**Issue by Jayphen** [fabrica-wp/fabrica-dev-kit#28]
I believe postcssImport should be first in the queue of plugin options inside `gulpfile.js`. It is currently placed last, which means any imported `.pcss` files do not benefit from nesting, mixins, etc.

Is there some reason it was placed last that I am missing?

**Comment by tiojoca** [comment]
You're right @Jayphen, thanks for pointing that out. We've fixed this and will published the changes soon.
