### ISSUE TITLE
[Fabrica] ⚠️  Could not find dependency 'composer'.

### ISSUE THREAD

**Issue by enguerranws** [fabrica-wp/fabrica-dev-kit#3]
Hi,

I'm getting this issue trying to run `./setup.rb`. 
`[Fabrica] ⚠️  Could not find dependency 'composer'.`

So I run `composer -v`, just to be sure, which logs : `Composer version 1.4.1 2017-03-10 09:29:45`

What do I miss?

**Comment by tiojoca** [comment]
Hey,

Are you using any virtual environment tool (`rbenv`, `rvm`, `virtualenv`, etc.)?

Do you get any error if you run `if hash composer; then echo "ok"; fi` in the command shell? What about `ruby -e "puts 'ok' if system 'hash composer'"`?

**Comment by enguerranws** [comment]
Hi, 

Thanks for your help. Both of the commands you gave me return: `composer: not found`.

**Comment by tiojoca** [comment]
Thanks for trying that out. That's odd, `hash composer` should detect the executable if available. Can you try these two other alternative ways to see if they work in your system:
`if command -v composer; then echo 'ok'; else echo 'not found'; fi`
and
`if type composer >/dev/null; then echo 'ok'; fi`

**Comment by maxperei** [comment]
hi there, same problem, you figured out what happen ?

**Comment by enguerranws** [comment]
@tiojoca 
The first command returns: 
> alias composer='php /usr/local/bin/composer.phar'
> ok

and the second returns:
> ok

I'm guessing `composer` isn't available in my Ruby env?

**Comment by maxperei** [comment]
@enguerranws very good point, you should `gem install composer` and this solve our problem

**Comment by fewerflatlands** [comment]
@maxperei @enguerranws thanks for looking at this together – can you confirm if `gem install composer` does the trick?

**Comment by enguerranws** [comment]
Yes it does! I had to overwrite my previous install of composer with the Ruby Gem version.
Thanks!

**Comment by fewerflatlands** [comment]
Great, good to get to the bottom of this.
