### ISSUE TITLE
Question re config/wordmove.yml ?

### ISSUE THREAD

**Issue by bongoman** [fabrica-wp/fabrica-dev-kit#30]
Just getting stuck on this file — do I `cp` this from the config/ directory to the main project directory as `Movefile` and is the `wordmove push` command then run from the main project directory?

**Comment by fewerflatlands** [comment]
Hi @bongoman, Gulp takes care of the copy procedure (and also adds the local development environment settings automatically). So you specify your staging/production environment settings in`config/wordmove.yml`, and when you run `gulp` or `gulp build` it'll render a valid Movefile. 

You then use `wordmove push` from the main project directory.

If you are having problems let us know.
