### ISSUE TITLE
[Question] Multiple sites in different branches.

### ISSUE THREAD

**Issue by zomars** [fabrica-wp/fabrica-dev-kit#31]
Can it be done? Or what would be a recommended approach for multiple sites that share the same theme, plugins, except the DB (or content.

**Comment by fewerflatlands** [comment]
The recommended approach would be to use a single local installation of FDK for development, and then create a `Movefile` with multiple environments' upload credentials, then using `wordmove` with the `-e` flag to specify the environment for each operation. In this way push theme, plugins, etc to several different independent installations.

See https://github.com/welaika/wordmove/wiki/Usage-and-flags-explained
