### ISSUE TITLE
Error: /usr/bin/env: ‘node --harmony’: No such file or directory

### ISSUE THREAD

**Issue by lcdessantos** [fabrica-wp/fabrica-dev-kit#32]
I got this error on Ubuntu 16.04, Node 6.10:

```
/usr/bin/env: ‘node --harmony’: No such file or directory
```

After some googling I discovered that `env` in Linux doesn't support arguments. So I solved the problem by removing the flag `--harmony` from the shebang in the file `fabrica-dev-kit/index.js`.

Please consider removing this flag in the next release.

**Comment by tiojoca** [comment]
We've added this workaround to fix this problem in Linux: http://sambal.org/2014/02/passing-options-node-shebang-line/ . This will be available when the next version of FDK is published.

Note that we mainly support Mac and test in Linux or other OSes only occasionally. Please let us know if you come across any other issues.

**Comment by lcdessantos** [comment]
Sure.
