### ISSUE TITLE
`fdk remove` not working

### ISSUE THREAD

**Issue by bongoman** [fabrica-wp/fabrica-dev-kit#33]
`fdk remove` as referenced in the readme doesn't seem to exist as a command?

**Comment by tiojoca** [comment]
Are you using FDK's latest version? Note that this command is only available on folders and subfolders of a project set up by FDK.

**Comment by tiojoca** [comment]
Marking this as closed. Please make sure you're running `fdk` inside an FDK project folder. Only a few `fdk` commands are available when executing outside a folder that's already been initialized and set up.
