### ISSUE TITLE
Unable to run gulp on first install

### ISSUE THREAD

**Issue by bradymwilliams** [fabrica-wp/fabrica-dev-kit#4]
```
➜  dev git:(master) /usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by fewerflatlands** [comment]
Hi @bradymwilliams, looks like you need to update the version of `gulp-cli` installed globally. Check the version with `gulp -v` – it needs to be 1.2.2. If it's below that, update with `npm install gulpjs/gulp-cli -g`.

Then try running `./setup.rb --reinstall` which will hopefully save you having to delete everything and start over. Let me know how you get on!

**Comment by grahamharper** [comment]
I'm having the same issue. I tried `npm install gulpjs/gulp-cli -g` followed by `./setup.rb --reinstall` but still getting the same error.

**Comment by fewerflatlands** [comment]
@grahamharper OK, thanks for the feedback, can you confirm the output from `gulp -v` and we'll investigate further.

**Comment by grahamharper** [comment]
I actually just managed to resolve the issue, I had an old version of gulp that `npm rm --global gulp` wouldn't remove so running `sudo rm /usr/local/bin/gulp` got rid of it so I could run `npm install --global gulp-cli` so gulp is working now.

Thanks.

**Comment by fewerflatlands** [comment]
Ah that's good to hear, perhaps @bradymwilliams could try that too if still having problems. Thanks a lot.
