### ISSUE TITLE
Enhancement: ES6 compilation

### ISSUE THREAD

**Issue by sqbiz** [fabrica-wp/fabrica-dev-kit#9]
I write all of my JS in ES6, but my webpack skills aren't hot enough to try to mess with your super clean config!

(Otherwise, i'm super impressed with Fabrica, the amount of headache you are saving the internet is endless!)

**Comment by tiojoca** [comment]
Thanks a lot @sqbiz! We're considering adding this. In the meantime, `gulpfile.js` is meant to be changed to fit the projects' needs so you can try and add this yourself to your project if you like.

Just add the necessary dependencies in `dev/`:
```
yarn add --dev babel-loader babel-core babel-preset-env webpack
```
or if you're using `npm`:
```
npm install --save-dev babel-loader babel-core babel-preset-env webpack
```

then in `gulpfile.js` change the webpack-stream call to:
```
.pipe(webpack({
	output: {filename: 'main.js'},
	module: {
		rules: [{
			test: /\.js$/,
			exclude: /node_modules/,
			use: {
				loader: 'babel-loader',
				options: {
					presets: ['env']
				}
			}
		}]
	}
}, require('webpack')))
```

To avoid JSHint warnings you should also add a `.jshintrc` file in `dev/` with: `{ "esnext": true }`

Webpack should now use the Babel loader to transpile your JS.

**Comment by sqbiz** [comment]
Thank you!!


  ✘ [www.standard-quality.biz](http://www.standard-quality.biz/) ✿

**Comment by sqbiz** [comment]
I had to do this a little differently to get it working, my setup is:

```
var webpackConfig = {
	output: { filename: 'main.js' },
	module: {
		loaders: [
			{
				test: /\.js$/,
				loader: 'babel-loader',
				query: {
					presets: ['es2015']
				}
			}
		]
	},
}
```

```
	return gulp.src(path.scriptMain)
		.pipe(jshint())
		.pipe(jshint.reporter())
		.pipe(changed(base.theme + dest.scripts))
		.pipe(webpack(webpackConfig))
            // ...

```

versions in package.json:

```
  "devDependencies": {
   // ...
    "babel-core": "^6.24.1",
    "babel-loader": "^7.0.0",
    "babel-preset-env": "^1.5.1",
    "webpack-stream": "^3.2.0"
   // ..
   }

```
